dist: trusty

sudo: required

language: php

php:
  - 7.0

services:
- mysql

addons:
apt:
  sources:
    - mysql-5.7-trusty
  packages:
    - mysql-server

env:
  - TRAVIS_NODE_VERSION="6"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - node_modules

install:
    - composer install --prefer-dist
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - npm install --no-optional
    - cp .env.travis .env
    - chmod -R o+w storage/
    - mysql -e 'create database trip2;'
    - php artisan migrate:refresh
    - npm run build

script:
    - ./vendor/bin/phpunit --verbose

notifications:
    email: false
    slack: tripikad:Rb20AN0r1arWwhxIBl9DNaZ5