dist: trusty

#sudo: true

language: php

php:
  - 7.0

#services:
#  - mysql

env:
  - TRAVIS_NODE_VERSION="8"

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.yarn-cache
    - node_modules
    - vendor

install:
    - bash .travis.install-mysql-5.7.sh
    - composer install --no-interaction
    - cp .env.travis .env
    - chmod -R o+w storage/
    - chmod -R o+w bootstrap/cache/
    - mysql -e 'create database trip2;'
    - php artisan migrate:refresh
    - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - npm install --global yarn
    - yarn
    - npm run build

script:
    - ./vendor/bin/phpunit

notifications:
    email: false
    slack: tripikad:Rb20AN0r1arWwhxIBl9DNaZ5