dist: trusty

sudo: true

services:
  - mysql

before_script:
  - bash .travis.install-mysql-5.7.sh
  - npm install -g npm
  - npm install -g gulp-cli

language: php

php:
  - 7.0

env:
  - TRAVIS_NODE_VERSION="6"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - node_modules

install:
    - composer install --prefer-dist
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - npm install --no-optional
    - cp .env.travis .env
    - chmod -R o+w storage/
    - mysql -e 'create database trip2;'
    - php artisan migrate:refresh
    - gulp
    - gulp v1

script:
    - ./vendor/bin/phpunit

notifications:
    email: false
    slack: tripikad:Rb20AN0r1arWwhxIBl9DNaZ5